[GO BACK] to the old version of the workflow

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -1,26 +1,53 @@
-name: Workflow
+name: Push mirror
 
 on:
   push:
     branches:
-      - main
+      - 'main'
   pull_request:
     branches:
-      - main
+      - 'dev'
 
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2027/B-CPP-500-LYN-5-2-rtype-noe.pereira.git"
 
 jobs:
-  prevent_direct_push:
-    if: github.event_name == 'push'
+  build_and_verify:
     runs-on: ubuntu-latest
     steps:
-      - name: Check for Direct Push
-        shell: bash
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Install Dependencies
         run: |
-          if [[ -z "$GITHUB_HEAD_REF" ]]; then
-            echo "❌ Direct pushes to 'main' are not allowed. Please create a pull request."
-            exit 1
-          else
-            echo "✅ Push is from a pull request. Proceeding."
+          sudo apt-get update -y
+          sudo apt-get install -y cmake g++ make libconfig++-dev
+
+      - name: Verify Dependencies
+        run: |
+          dpkg -l | grep libconfig++-dev || { echo "libconfig++-dev not found!"; exit 1; }
+
+      - name: Build R-Type
+        run: cmake --build build
+
+      - name: Verify Executables
+        run: |
+          test -f build/r-type_server || { echo "r-type_server not found!"; exit 1; }
+          test -f build/r-type_client || { echo "r-type_client not found!"; exit 1; }
+
+  push_to_mirror:
+    runs-on: ubuntu-latest
+    needs: build_and_verify
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Push to Mirror Repository
+        uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url:
+            ${{ env.MIRROR_URL }}
+          ssh_private_key:
+            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
